import { hexDigit, ipv4DigitValidator, ipv4Validator, ipV6GroupValidator } from '../ip-addr';

test('ipDigit', () => {
  expect(ipv4DigitValidator).toMatchString('255');
  expect(ipv4DigitValidator).not.toMatchString('256');
  expect(ipv4DigitValidator).toMatchString('25');
  expect(ipv4DigitValidator).not.toMatchString('25.5');
  expect(ipv4DigitValidator).toMatchString('249');
  expect(ipv4DigitValidator).toMatchString('100');
  expect(ipv4DigitValidator).toMatchString('199');
  expect(ipv4DigitValidator).not.toMatchString('1000');
  expect(ipv4DigitValidator).not.toMatchString('100.');
  expect(ipv4DigitValidator).toMatchString('000');
  expect(ipv4DigitValidator).toMatchString('00');
  expect(ipv4DigitValidator).toMatchString('0');
  expect(ipv4DigitValidator).not.toMatchString('000.0');
  expect(ipv4DigitValidator).not.toMatchString('00.0');
  expect(ipv4DigitValidator).not.toMatchString('0.0');
});

test('hexDigit', () => {
  expect(hexDigit).toMatchString('0');
  expect(hexDigit).toMatchString('1');
  expect(hexDigit).toMatchString('2');
  expect(hexDigit).toMatchString('3');
  expect(hexDigit).toMatchString('4');
  expect(hexDigit).toMatchString('5');
  expect(hexDigit).toMatchString('6');
  expect(hexDigit).toMatchString('7');
  expect(hexDigit).toMatchString('8');
  expect(hexDigit).toMatchString('9');
  expect(hexDigit).toMatchString('a');
  expect(hexDigit).toMatchString('b');
  expect(hexDigit).toMatchString('c');
  expect(hexDigit).toMatchString('d');
  expect(hexDigit).toMatchString('e');
  expect(hexDigit).toMatchString('f');
  expect(hexDigit).not.toMatchString('g');
  expect(hexDigit).not.toMatchString('h');
  expect(hexDigit).toMatchString('A');
  expect(hexDigit).toMatchString('B');
  expect(hexDigit).toMatchString('C');
  expect(hexDigit).toMatchString('D');
  expect(hexDigit).toMatchString('E');
  expect(hexDigit).toMatchString('F');
  expect(hexDigit).not.toMatchString('G');
  expect(hexDigit).not.toMatchString('H');
});

test('ipV6GroupValidator', () => {
  expect(ipV6GroupValidator).toMatchString('0');
  expect(ipV6GroupValidator).toMatchString('00');
  expect(ipV6GroupValidator).toMatchString('000');
  expect(ipV6GroupValidator).toMatchString('0000');
  expect(ipV6GroupValidator).not.toMatchString('00000');
  expect(ipV6GroupValidator).toMatchString('1');
  expect(ipV6GroupValidator).toMatchString('01');
  expect(ipV6GroupValidator).toMatchString('001');
  expect(ipV6GroupValidator).toMatchString('0001');
  expect(ipV6GroupValidator).not.toMatchString('00001');
  expect(ipV6GroupValidator).toMatchString('f');
  expect(ipV6GroupValidator).toMatchString('ff');
  expect(ipV6GroupValidator).toMatchString('fff');
  expect(ipV6GroupValidator).toMatchString('ffff');
  expect(ipV6GroupValidator).not.toMatchString('fffff');
  expect(ipV6GroupValidator).toMatchString('a');
  expect(ipV6GroupValidator).toMatchString('aa');
  expect(ipV6GroupValidator).toMatchString('aaa');
  expect(ipV6GroupValidator).toMatchString('aaaa');
  expect(ipV6GroupValidator).not.toMatchString('aaaaa');
  expect(ipV6GroupValidator).toMatchString('A');
  expect(ipV6GroupValidator).toMatchString('AA');
  expect(ipV6GroupValidator).toMatchString('AAA');
  expect(ipV6GroupValidator).toMatchString('AAAA');
  expect(ipV6GroupValidator).not.toMatchString('AAAAA');
  expect(ipV6GroupValidator).not.toMatchString('g');
  expect(ipV6GroupValidator).not.toMatchString('gg');
  expect(ipV6GroupValidator).not.toMatchString('ggg');
  expect(ipV6GroupValidator).not.toMatchString('gggg');
  expect(ipV6GroupValidator).toMatchString('2001');
  expect(ipV6GroupValidator).toMatchString('Db8');
  expect(ipV6GroupValidator).toMatchString('8');
  expect(ipV6GroupValidator).toMatchString('800');
  expect(ipV6GroupValidator).toMatchString('200C');
  expect(ipV6GroupValidator).toMatchString('417A');
});

test('ipv4Validator', () => {
  expect(ipv4Validator).toMatchString('255.255.255.255');
  expect(ipv4Validator).not.toMatchString('255:255:255:255');
  expect(ipv4Validator).not.toMatchString('256.256.256.256');
  expect(ipv4Validator).not.toMatchString('255.255.255.255.255');
  expect(ipv4Validator).not.toMatchString('255.255.255');
  expect(ipv4Validator).toMatchString('10.0.0.128');
  expect(ipv4Validator).not.toMatchString('10.0.0.128.');
  expect(ipv4Validator).not.toMatchString('.....');
});
