import { hexDigit } from '../shared';

test('hexDigit', () => {
  expect(hexDigit).toMatchString('0');
  expect(hexDigit).toMatchString('1');
  expect(hexDigit).toMatchString('2');
  expect(hexDigit).toMatchString('3');
  expect(hexDigit).toMatchString('4');
  expect(hexDigit).toMatchString('5');
  expect(hexDigit).toMatchString('6');
  expect(hexDigit).toMatchString('7');
  expect(hexDigit).toMatchString('8');
  expect(hexDigit).toMatchString('9');
  expect(hexDigit).toMatchString('a');
  expect(hexDigit).toMatchString('b');
  expect(hexDigit).toMatchString('c');
  expect(hexDigit).toMatchString('d');
  expect(hexDigit).toMatchString('e');
  expect(hexDigit).toMatchString('f');
  expect(hexDigit).not.toMatchString('g');
  expect(hexDigit).not.toMatchString('h');
  expect(hexDigit).toMatchString('A');
  expect(hexDigit).toMatchString('B');
  expect(hexDigit).toMatchString('C');
  expect(hexDigit).toMatchString('D');
  expect(hexDigit).toMatchString('E');
  expect(hexDigit).toMatchString('F');
  expect(hexDigit).not.toMatchString('G');
  expect(hexDigit).not.toMatchString('H');
});
